<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

// Remove default loop.
remove_action( 'genesis_loop', 'genesis_do_loop' );

add_action( 'genesis_loop', 'genesis_404' );
/**
 * This function outputs a 404 "Not Found" error message.
 *
 * @since 1.6
 */
function genesis_404() {

	genesis_markup(
		[
			'open'    => '<section class="page-not-found-block page-not-found">
    <div class="container">',
			'context' => 'entry-404',
		]
	);


	genesis_markup(
		[
			'open'    => '<div class="d-flex justify-content-center"><h2 %s>',
			'close'   => '</h2>',
			'content' => apply_filters( 'genesis_404_entry_title', __( '404', 'genesis' ) ),
			'context' => 'section-title',
		]
	);

	$genesis_404_content = sprintf(
		/* translators: %s: URL for current website. */
		__( 'Oops! Page Not Found' ),
		esc_url( trailingslashit( home_url() ) )
	);

	$genesis_404_content = sprintf( '<span class="text1">%s</span>', $genesis_404_content );

	/**
	 * The 404 content (wrapped in paragraph tags).
	 *
	 * @since 2.2.0
	 *
	 * @param string $genesis_404_content The content.
	 */
	$genesis_404_content = apply_filters( 'genesis_404_entry_content', $genesis_404_content );

	$genesis_404_content_desc = sprintf(
		/* translators: %s: URL for current website. */
		__( 'The page you were looking for could not be found.' ),
		esc_url( trailingslashit( home_url() ) )
	);
	$genesis_404_content_btn = sprintf(
		/* translators: %s: URL for current website. */
		__( '<a href="%s" class="tx-ctm-btn">Back To Home</a>' ),
		esc_url( trailingslashit( home_url() ) )
	);
	$genesis_404_content_desc = sprintf( '<span class="text2">%s</span>', $genesis_404_content_desc  );
    
	/**
	 * The 404 content (wrapped in paragraph tags).
	 *
	 * @since 2.2.0
	 *
	 * @param string $genesis_404_content The content.
	 */
	$genesis_404_content_desc = apply_filters( 'genesis_404_content_desc', $genesis_404_content_desc );

	$genesis_404_content_btn = apply_filters( 'genesis_404_content_btn', $genesis_404_content_btn );
	genesis_markup(
		[
			'open'    => '<div class="page-not-found-content">',
			'content' => $genesis_404_content,
			'context' => 'entry-content',
		]
	);	
	genesis_markup(
		[
			'content' => $genesis_404_content_desc,
			'context' => 'entry-content',
			'close'  => '</div></div>',
		]
	);
	genesis_markup(
		[
			'content' => $genesis_404_content_btn,
		]
	);
	genesis_markup(
		[
			'close'   => '</div></section>',
			'context' => 'entry-404',
		]
	);

}
?>

<?php
genesis();
